version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5
        environment:
          USE_CCI: true
          RAILS_ENV: test
          ED2_DB_PASSWORD: '12341234'
          ED2_DB_PORT: '3306'
          ED2_DB_USERNAME: root
          ED2_DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.7.22
        environment:
          MYSQL_DATABASE: ed2_test
          MYSQL_ROOT_PASSWORD: '12341234'
    working_directory: ~/app
    steps:
      - run:
          name: Update Debian Packages
          command: |
            echo "deb http://http.debian.net/debian stretch-backports main" | sudo tee -a /etc/apt/sources.list
            sudo apt-get update -qq
            sudo apt-get upgrade -qq
            sudo apt-get install -y -f software-properties-common build-essential default-libmysqlclient-dev mariadb-client nodejs make apt-utils
      - checkout
      - restore_cache:
          key: gemfile-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby Dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: gemfile-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
            - tmp/zips
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Copy local_env.yml
          command: cp config/local_env.example.yml config/local_env.yml
      - run:
          name: Copy settings.yml
          command: cp config/settings.example.yml config/settings.yml
      - run:
          name: Create DB
          command: bundle exec rake db:create db:schema:load --trace
      - run:
          name: Run Tests
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: /tmp/circle-junit
