# Background job queue
# Docker
#ACTIVE_JOB_QUEUE_ADAPTER: sidekiq

# Rails defaults
# Docker
RAILS_CACHE_STORE_URL: memcache
RAILS_LOG_TO_STDOUT: 'true'

# Database
ED2_DB_PASSWORD: '12341234'
ED2_DB_PORT: '3306'
ED2_DB_USERNAME: root
# ED2_DB_HOST: 127.0.0.1
# Docker
ED2_DB_HOST: db
# Production/Staging only; not needed for development/test as these are set in database.yml
ED2_DB: development

# Secret key for Devise and Rails security
ED2_SECRET_KEY_BASE: bobross1234bobross1234bobross1234bobross1234bobross1234

# CAS authentication
ED2_CAS_BASE_URL: 'https://FQDN/cas'
ED2_CAS_VALIDATE_URL: 'https://FQDN/cas/samlValidate'

# Capistrano deployment log path
ED2_DEPLOYED_REVISION_LOG: /path/to/app/revisions.log

# The Repository that ED2 will publish works to
REPOSITORY_URL: 'http://hyrax.server'
REPOSITORY_SEARCH_URL: '/catalog.json?q="{value}"&op=AND&{property}="{value}"'
REPOSITORY_ADMIN_SET_URL: '/admin/admin_sets.json'
REPOSITORY_WORKFLOW_URL: '/concern/workflow_actions/{work_id}'
REPOSITORY_UPLOAD_URL: '/uploads'
REPOSITORY_AUTHENTICATION_TOKEN: '12345'
REPOSITORY_AUTHENTICATION_USERNAME: 'ed2user@hyrax.server'
REPOSITORY_PUBLISH_WORK_TYPE: Article
REPOSITORY_PUBLISH_ADMIN_SET_NAME: Self Deposit
REPOSITORY_PUBLISH_REQUIRES_WORKFLOW_APPROVAL: 'false'
REPOSITORY_PUBLISH_RIGHTS_STATEMENT: 'http://rightsstatements.org/vocab/InC/1.0/'
REPOSITORY_PUBLISH_LICENSE: 'http://creativecommons.org/licenses/by/4.0/'
REPOSITORY_PUBLISH_RESOURCE_TYPE: 'Article'

# Redis for background jobs and notifications
ED2_REDIS_PORT: '6379'
ED2_REDIS_HOST: localhost
# Docker
#ED2_REDIS_HOST: redis

# Email configurations
ED2_EMAIL_FROM: 'user@server.com'
ED2_APPLICATION_HOST_NAME: 'localhost:3000'
ED2_EMAIL_DELIVERY_METHOD: 'test'

# Web Of Science Search Terms
ED2_WOS_SEARCH_TERMS:
  - Oregon State University
  - Oregon State Univ

# OSU API
OSU_API_URL: 'https://api.server'
OSU_API_OAUTH2_TOKEN: '/oauth2/token'
OSU_API_DIRECTORY_SEARCH: '/v1/directory'
OSU_API_CONSUMER_KEY: 'xxx123abc'
OSU_API_CONSUMER_SECRET: 'abc123xxx'
