# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f822c581c4a83b555e43656964c902b386f80a8b5dd45dd8520ccd22880684850e4e517ac13085751fc67e36df2f586cc30cfdbc0f97cb6cd158e2d7b4ff9594

test:
  secret_key_base: 6b88b62231e6badfc8479c237a2a5bd79bbcdd55eb2f27d0a42b8bdb64cd619bda8741ec73f439c36ae4624aa6b94a9c5ddcb481228439b3dc240db4a2eac464

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["ED2_SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["ED2_SECRET_KEY_BASE"] %>
